/**
 * @module firebase/exports
 *
 * This file is automatically generated by scripts/generateFirebaseExports.ts.
 * It contains the Firebase Functions constants used in the generators. We don't
 * want to import them directly from firebase-functions package because when we
 * do, it prints annoying warning:
 *
 * > {"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
 */

/**
 * The available Firebase Functions regions.
 */
export const firebaseRegions: FirebaseRegion[] = [
  "us-central1",
  "us-east1",
  "us-east4",
  "us-west2",
  "us-west3",
  "us-west4",
  "europe-central2",
  "europe-west1",
  "europe-west2",
  "europe-west3",
  "europe-west6",
  "asia-east1",
  "asia-east2",
  "asia-northeast1",
  "asia-northeast2",
  "asia-northeast3",
  "asia-south1",
  "asia-southeast1",
  "asia-southeast2",
  "northamerica-northeast1",
  "southamerica-east1",
  "australia-southeast1",
];

/**
 * The Firebase Functions region.
 */
export type FirebaseRegion =
  | "us-central1"
  | "us-east1"
  | "us-east4"
  | "us-west2"
  | "us-west3"
  | "us-west4"
  | "europe-central2"
  | "europe-west1"
  | "europe-west2"
  | "europe-west3"
  | "europe-west6"
  | "asia-east1"
  | "asia-east2"
  | "asia-northeast1"
  | "asia-northeast2"
  | "asia-northeast3"
  | "asia-south1"
  | "asia-southeast1"
  | "asia-southeast2"
  | "northamerica-northeast1"
  | "southamerica-east1"
  | "australia-southeast1";

/**
 * The available Firebase Functions memory options.
 */
export const firebaseMemoryOptions: FirebaseMemoryOption[] = [
  "128MB",
  "256MB",
  "512MB",
  "1GB",
  "2GB",
  "4GB",
  "8GB",
];

/**
 * The Firebase Functions memory option.
 */
export type FirebaseMemoryOption =
  | "128MB"
  | "256MB"
  | "512MB"
  | "1GB"
  | "2GB"
  | "4GB"
  | "8GB";
